export enum AppRoutes {
    dashboard = "/",
    settings = "/settings",
    bibliography = "/bibliography",
    dictionary = "/dictionary",
    snippets = "/snippets",
    kanbanBoards = "/kanban-boards",
    equations = "/equations",
    viewMdxNote = "/mdx",
    splitViewEditMdx = "/mdx-split-view",
    embeddedDocs = "/embedded_docs",
    bookmarks = "/bookmarks",
    taskLists = "/taskLists",
    search = "/search",
    onboarding = "/onboarding",
}
