export enum AppRoutes {
    dashboard = "/",
    settings = "/settings",
    pdf = "/pdf",
    bibliography = "/bibliography",
    dictionary = "/dictionary",
    snippets = "/snippets",
    kanbanBoards = "/kanban-boards",
    equations = "/equations",
    viewMdxNote = "/mdx",
    splitViewEditMdx = "/mdx-split-view",
    embeddedDocs = "/embedded-docs",
    bookmarks = "/bookmarks",
    taskLists = "/taskLists",
    search = "/search",
    semanticSearch = "/semantic-search",
    onboarding = "/onboarding",
    aiMainChat = "/aiChat",
}
