// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../../frb_generated.dart';
import '../../../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `save_many`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MdxNotesRepository>>
abstract class MdxNotesRepository implements RustOpaqueInterface {
  FlusterDb get db;

  String get tableName;

  set db(FlusterDb db);

  set tableName(String tableName);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MdxNotesRepository> newInstance({required FlusterDb db}) =>
      RustLib.instance.api
          .crateApiRepositoriesNotesMdxMdxNotesRepositoryMdxNotesRepositoryNew(
            db: db,
          );
}
