[package]
name = "fluster_models"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
gray_matter.workspace = true
ignore = "0.4.23"
markdown = "1.0.0"
mdxjs = "1.0.0"
serde.workspace = true
thiserror = { workspace = true }
fluster_test_utils = { path = "../fluster_test_utils/" }
fluster_db = { path = "../fluster_db/" }
fluster_types = { path = "../fluster_types/" }
miette = { version = "7.5.0", features = ["fancy"] }
surrealdb.workspace = true
futures = "0.3.31"
tokio = "1.44.2"
log = "0.4.27"
regex = "1.11.1"
time = { version = "0.3.41", features = ["macros", "serde", "serde-human-readable", "serde-well-known"] }
filetime = "0.2.25"
rayon = "1.10.0"
