[package]
name = "fluster_types"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
surrealdb = { workspace = true, features = ["kv-rocksdb"] }
thiserror.workspace = true
flutter_rust_bridge = { workspace = true }
diesel-async = "0.5.2"
