[package]
name = "fluster_types"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
flutter_rust_bridge = { workspace = true }
diesel-async = "0.5.2"
diesel = { workspace = true, features = [
    "postgres",
    "postgres_backend",
    "serde_json",
    "chrono",
    "r2d2",
] }
rayon.workspace = true
tsify = "0.5.5"
strum = "0.27.1"
strum_macros = "0.27.1"
wasm-bindgen.workspace = true
enum-iterator = "2.1.0"
