[workspace]
resolver = "2"
members = [
    "apps/fluster/src-tauri",
    "packages/fluster_grpc",
    "packages/fluster_test_utils",
    "packages/fluster_lua", "packages/fluster_internal_workspace/rust",
]


[workspace.package]
version = "0.0.1"
authors = ["Andrew Iglinski"]
description = "Be less dum."
documentation = "fluster-one.vercel.app"
edition = "2021"

[workspace.lints.rust]
unused_crate_dependencies = "warn"

[workspace.dependencies]
serde = "1.0.219"
serde_json = "1.0.140"
include_dir = "0.7.4"
mlua = { version = "0.10", features = ["lua54", "vendored"] }

# TODO: Remove this and the reliance on console_subscriber when actually building for production.
# TEMP: Move this to each nested project if necessary
# [build]
# rustflags = ["--cfg", "tokio_unstable"]

[profile.dev.package.lancedb]
opt-level = 1

[profile.release]
lto = true
strip = true
opt-level = 3
# panic = 'abort'
codegen-units = 1

# [patch.crates-io]
# chrono = { version = "0.4.41" }
