[workspace]
resolver = "2"
members = [
    "apps/fluster/src-tauri",
    "packages/fluster_grpc",
    "packages/fluster_test_utils",
    "packages/fluster_lua",
]


[workspace.package]
version = "0.0.1"
authors = ["Andrew Iglinski"]
description = "Be less dum."
documentation = "ulld.vercel.app"
edition = "2021"

[workspace.lints.rust]
unused_crate_dependencies = "warn"

[workspace.dependencies]
serde = "1.0.219"
serde_json = "1.0.140"
gray_matter = "0.2.8"
typeshare = "1.0.4"
wasm-bindgen = "0.2.100"
rayon = "1.10.0"
include_dir = "0.7.4"
dirs = "6.0.0"
tracing = "0.1"
tracing-subscriber = "0.3.0"
mlua = { version = "0.10", features = ["lua54", "vendored"] }
log4rs = { version = "1.3.0", features = [
    "rolling_file_appender",
    "size_trigger",
    "json_encoder",
    "threshold_filter",
] }
chrono = { version = "0.4.39" }
thiserror = "2.0.12"
dotenvy = "0.15"

# TODO: Remove this and the reliance on console_subscriber when actually building for production.
# TEMP: Move this to each nested project if necessary
# [build]
# rustflags = ["--cfg", "tokio_unstable"]

[profile.dev.package.lancedb]
opt-level = 1

[profile.release]
lto = true
strip = true
opt-level = 3
panic = 'abort'
codegen-units = 1
