[workspace]
resolver = "2"
members = [
    "packages/fluster_native_interface/rust",
    "packages/fluster_grpc",
    "packages/fluster_db",
    "packages/fluster_test_utils",
    "packages/fluster_types",
    "packages/fluster_models",
    "packages/fluster_logger",
]


[workspace.package]
version = "0.0.1"
authors = ["Andrew Iglinski"]
description = "Be less dum."
documentation = "ulld.vercel.app"
edition = "2021"

[workspace.dependencies]
serde = "1.0.219"
serde_json = "1.0.140"
gray_matter = "0.2.8"
flutter_rust_bridge = "=2.9.0"
chrono = "0.4.40"
include_dir = "0.7.4"
dirs = "6.0.0"
tracing = "0.1"
tracing-subscriber = "0.3.0"
surrealdb = { version = "=2.2.1", features = [
    # "kv-surrealkv",
    "kv-rocksdb",
    "kv-surrealkv",
    "protocol-ws",
    "rustls",
] }
log4rs = { version = "1.3.0", features = [
    "rolling_file_appender",
    "size_trigger",
    "json_encoder",
    "threshold_filter",
] }
thiserror = "2.0.12"


# TODO: Remove this and the reliance on console_subscriber when actually building for production.
[build]
rustflags = ["--cfg", "tokio_unstable"]

[profile.release]
lto = true
strip = true
opt-level = 3
panic = 'abort'
codegen-units = 1
