name: fluster
publish_to: none
environment:
  sdk: ^3.8.0
packages:
  - packages/**
  - apps/**
scripts:
  build_desktop:
    name: Build Desktop Apps
    steps:
      - melos run generate_icons
      - melos run build_rust
      - melos run build_fluster
