name: fluster
publish_to: none
environment:
  sdk: ^3.7.0
packages:
  - packages/**
  - apps/**
scripts:
  test_flutter:
    name: Test Flutter
    description: Test the Flutter & Dart side of the workspace.
    run: flutter test $FLUSTER_NATIVE_ROOT/apps/fluster --coverage --no-pub && flutter pub run test_cov_console --file=$FLUSTER_NATIVE_ROOT/apps/fluster/coverage/lcov.info
  test_rust:
    name: Test with coverage
    description: Test rust throughout the workspace.
    run: cargo llvm-cov --html
  generate_icons:
    name: Generate Icons
    description: Generate icons using flutter_launcher_icons.
    run: cd $FLUSTER_NATIVE_ROOT/apps/fluster/ && dart run flutter_launcher_icons -f $FLUSTER_NATIVE_ROOT/apps/fluster/flutter_launcher_icons.yaml
  # run_builders:
  #   name: Run Builders
  #   run:
  build_rust:
    name: buildRust
    description: Compile using flutter_rust_bridge in the fluster_native_interface package.
    run: flutter_rust_bridge_codegen generate ./packages/fluster_native_interface
  build_fluster:
    name: Build Fluster
    description: Builds the fluster flutter app alone.
    run: flutter_rust_bridge_codegen generate ./packages/fluster_native_interface
  build_desktop:
    name: Build Desktop Apps
    steps:
      - melos run generate_icons
      - melos run build_rust
      - melos run build_fluster
