packages:
  - "apps/fluster"
  - "apps/plugin_template"
  - "packages/fluster_ts"
  - "packages/fluster_embedded_components"
  - "packages/fluster_native_interface/typescript"
  - "packages/fluster_ui"
  - "packages/fluster_config"
