[package]
name = "fluster_db"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
chrono = { workspace = true }
flutter_rust_bridge = { workspace = true }
gray_matter = { workspace = true }
mdxjs = "0.3.4"
serde = { workspace = true, features = ["derive"] }
surrealdb = { workspace = true, features = [
    "kv-surrealkv",
    "protocol-ws",
    "rustls",
] }
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
fluster_test_utils = { path = "../../fluster_test_utils" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
