// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `test_fn`

/// Reeturns the straightforward v8 context, without all of the Fluster specific modifications
/// applied.
Future<void> getV8Min({required int nThreads}) => RustLib.instance.api
    .crateApiJavascriptHandlersGetV8EnvironmentGetV8Min(nThreads: nThreads);

/// Returns a v8 engine with all of Fluster's functions applied and made to be accessibile
/// globally.
Future<void> getV8Full({required int nThreads}) => RustLib.instance.api
    .crateApiJavascriptHandlersGetV8EnvironmentGetV8Full(nThreads: nThreads);
