# This file was generated by [py-rs](https://github.com/Blue-Chestnut/py-rs). Do not edit this file manually.
from pydantic import BaseModel

from .AiChatMessageData import AiChatMessageModel
from .AiChatMessageData import AiChatModel


class AiChatData(BaseModel):
    """
    A utility struct that combines the ChatModel, AiChatMessageResponse, and AiChatMessageRequest
    entities into a single struct.
    """

    chat: AiChatModel
    messages: list[AiChatMessageModel]
