// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Map < SettingPageId , SettingPage >>>
abstract class MapSettingPageIdSettingPage implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Settings>>
abstract class Settings implements RustOpaqueInterface {
  bool get isSeeded;

  MapSettingPageIdSettingPage get pages;

  set isSeeded(bool isSeeded);

  set pages(MapSettingPageIdSettingPage pages);
}
