[package]
name = "fluster_logger"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
dirs.workspace = true
log4rs = { workspace = true }
thiserror = { workspace = true }
tracing.workspace = true
fluster_types = { path = "../fluster_types" }
log = "0.4.27"
