// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<FlusterDatabaseStatus> getDatabaseStatus() => RustLib.instance.api
    .crateApiDataInterfaceGetDatabaseStatusGetDatabaseStatus();

enum FlusterDatabaseStatus {
  /// NotInitialized is true when the database directory doesn't exist.
  notInitialized,

  ///  There's an error with the database that needs to be handled elsewhere.
  errorEncountered,

  /// Not connected is reserved for use in future remote database support.
  notConnected,

  /// Connected: Everything's honkey-dorey.
  connected,

  /// The state when the app initially starts, before the database status is returned from
  /// the async function.
  awaitingInitialPing,
}
