[package]
name = "fluster_native_interface"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
dirs = { workspace = true }
env_logger = "0.11.8"
flutter_rust_bridge = { workspace = true }
log = "0.4.27"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
fluster_rust_types = { path = "../../fluster_rust_types/" }
fluster_db = { path = "../../fluster_db/" }
regex = "1.11.1"
strsim = "0.11.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
