[package]
name = "fluster_native_interface"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
dirs = { workspace = true }
serde.workspace = true
flutter_rust_bridge = { workspace = true, features = ["chrono"] }
log = "0.4.27"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
fluster_types = { path = "../../fluster_types/" }
fluster_test_utils = { path = "../../fluster_test_utils/" }
fluster_logger = { path = "../../fluster_logger/" }
fluster_wasm = { path = "../../fluster_wasm/" }
fluster_db = { path = "../../fluster_db/" }
regex = "1.11.1"
strsim = "0.11.1"
ignore = "0.4.23"
gray_matter.workspace = true
rayon = { workspace = true }
crossbeam = "0.8.4"
crossbeam-channel = "0.5.15"
miette = { version = "7.5.0", features = ["fancy"] }
tokio = { version = "1.44.2", features = ["full"] }
slicestring = "0.3.3"
globset = "0.4.16"
fs_extra = "1.3.0"
lazy_static = "1.5.0"
console-subscriber = "0.4.1"
filetime = "0.2.25"
typeshare.workspace = true
anyhow = "1.0.98"
biblatex = "0.10.0"
rust-embed = "8.7.0"
langchain-rust = "4.6.0"
time = { version = "0.3.41", features = [
    "macros",
    "serde",
    "serde-human-readable",
    "serde-well-known",
] }
wasm-bindgen = { workspace = true }
tsify = "0.5.5"
enum-iterator = "2.1.0"
chrono = { workspace = true, features = ["serde"] }
diesel-async.workspace = true
diesel-derive-enum.workspace = true
diesel = { workspace = true, features = [
    "chrono",
    "postgres",
    "postgres_backend",
    "r2d2",
    "serde_json",
] }
dotenvy.workspace = true
serde_json.workspace = true
strum = { version = "0.27.1", features = ["strum_macros"] }
strum_macros = "0.27.1"
# rig-core = { version = "0.12.0", features = ["all"] }
# rig-surrealdb = "0.1.5"
# meilisearch-sdk = "0.28.0"

[build-dependencies]
flutter_rust_bridge_codegen = "2.9.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
