[package]
name = "fluster_grpc"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[[bin]] # Bin to run the HelloWorld gRPC server
name = "fluster-server"
path = "src/api/server.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "fluster-client"
path = "src/api/client.rs"

[dependencies]
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
prost = "0.13"
tonic = "0.13.0"
serde = { workspace = true }
serde_json = "1.0.140"
listenfd = "1.0.2"
prost-types = "0.13.5"
fluster_db = { path = "../fluster_db" }

[build-dependencies]
tonic-build = "0.13.0"
