[package]
name = "fluster_rust_types"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
gray_matter.workspace = true
ignore = "0.4.23"
markdown = "1.0.0"
mdxjs = "1.0.0"
serde.workspace = true
thiserror = { workspace = true }
fluster_test_utils = { path = "../fluster_test_utils/" }
miette = { version = "7.5.0", features = ["fancy"] }
