// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: settings.proto

package settings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettingType int32

const (
	SettingType_SETTING_TYPE_STRING_UNSPECIFIED SettingType = 0
	SettingType_SETTING_TYPE_INT                SettingType = 1
	SettingType_SETTING_TYPE_FLOAT              SettingType = 2
	SettingType_SETTING_TYPE_BOOL               SettingType = 3
)

// Enum value maps for SettingType.
var (
	SettingType_name = map[int32]string{
		0: "SETTING_TYPE_STRING_UNSPECIFIED",
		1: "SETTING_TYPE_INT",
		2: "SETTING_TYPE_FLOAT",
		3: "SETTING_TYPE_BOOL",
	}
	SettingType_value = map[string]int32{
		"SETTING_TYPE_STRING_UNSPECIFIED": 0,
		"SETTING_TYPE_INT":                1,
		"SETTING_TYPE_FLOAT":              2,
		"SETTING_TYPE_BOOL":               3,
	}
)

func (x SettingType) Enum() *SettingType {
	p := new(SettingType)
	*p = x
	return p
}

func (x SettingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SettingType) Descriptor() protoreflect.EnumDescriptor {
	return file_settings_proto_enumTypes[0].Descriptor()
}

func (SettingType) Type() protoreflect.EnumType {
	return &file_settings_proto_enumTypes[0]
}

func (x SettingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SettingType.Descriptor instead.
func (SettingType) EnumDescriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{0}
}

// /  A stripped down version of the SettingItem model.
type SettingField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingField) Reset() {
	*x = SettingField{}
	mi := &file_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingField) ProtoMessage() {}

func (x *SettingField) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingField.ProtoReflect.Descriptor instead.
func (*SettingField) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{0}
}

func (x *SettingField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SettingField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetUserSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*SettingField        `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsResponse) Reset() {
	*x = GetUserSettingsResponse{}
	mi := &file_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsResponse) ProtoMessage() {}

func (x *GetUserSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSettingsResponse) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserSettingsResponse) GetSettings() []*SettingField {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_settings_proto protoreflect.FileDescriptor

const file_settings_proto_rawDesc = "" +
	"\n" +
	"\x0esettings.proto\x12\vsettings.v1\":\n" +
	"\fSettingField\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"P\n" +
	"\x17GetUserSettingsResponse\x125\n" +
	"\bsettings\x18\x01 \x03(\v2\x19.settings.v1.SettingFieldR\bsettings*w\n" +
	"\vSettingType\x12#\n" +
	"\x1fSETTING_TYPE_STRING_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SETTING_TYPE_INT\x10\x01\x12\x16\n" +
	"\x12SETTING_TYPE_FLOAT\x10\x02\x12\x15\n" +
	"\x11SETTING_TYPE_BOOL\x10\x032\x10\n" +
	"\x0eSettingServiceB\fZ\n" +
	"./settingsb\x06proto3"

var (
	file_settings_proto_rawDescOnce sync.Once
	file_settings_proto_rawDescData []byte
)

func file_settings_proto_rawDescGZIP() []byte {
	file_settings_proto_rawDescOnce.Do(func() {
		file_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)))
	})
	return file_settings_proto_rawDescData
}

var file_settings_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_settings_proto_goTypes = []any{
	(SettingType)(0),                // 0: settings.v1.SettingType
	(*SettingField)(nil),            // 1: settings.v1.SettingField
	(*GetUserSettingsResponse)(nil), // 2: settings.v1.GetUserSettingsResponse
}
var file_settings_proto_depIdxs = []int32{
	1, // 0: settings.v1.GetUserSettingsResponse.settings:type_name -> settings.v1.SettingField
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_settings_proto_init() }
func file_settings_proto_init() {
	if File_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settings_proto_goTypes,
		DependencyIndexes: file_settings_proto_depIdxs,
		EnumInfos:         file_settings_proto_enumTypes,
		MessageInfos:      file_settings_proto_msgTypes,
	}.Build()
	File_settings_proto = out.File
	file_settings_proto_goTypes = nil
	file_settings_proto_depIdxs = nil
}
