import React, { createContext, useContext } from "react";

export interface SnippetState {
    languageFilter: Record<string, boolean>;
}

export enum SnippetActions {
    setLanguageFilters,
}

export const defaultInitialSnippetState: SnippetState = {
    languageFilter: {
        "1c": true,
        "1c-query": true,
        abap: true,
        "actionscript-3": true,
        ada: true,
        adoc: true,
        "angular-html": true,
        "angular-ts": true,
        apache: true,
        apex: true,
        apl: true,
        applescript: true,
        ara: true,
        asciidoc: true,
        asm: true,
        astro: true,
        awk: true,
        ballerina: true,
        bash: true,
        bat: true,
        batch: true,
        be: true,
        beancount: true,
        berry: true,
        bibtex: true,
        bicep: true,
        blade: true,
        bsl: true,
        c: true,
        "c#": true,
        "c++": true,
        cadence: true,
        cairo: true,
        cdc: true,
        clarity: true,
        clj: true,
        clojure: true,
        "closure-templates": true,
        cmake: true,
        cmd: true,
        cobol: true,
        codeowners: true,
        codeql: true,
        coffee: true,
        coffeescript: true,
        "common-lisp": true,
        console: true,
        coq: true,
        cpp: true,
        cql: true,
        crystal: true,
        cs: true,
        csharp: true,
        css: true,
        csv: true,
        cue: true,
        cypher: true,
        d: true,
        dart: true,
        dax: true,
        desktop: true,
        diff: true,
        docker: true,
        dockerfile: true,
        dotenv: true,
        "dream-maker": true,
        edge: true,
        elisp: true,
        elixir: true,
        elm: true,
        "emacs-lisp": true,
        erb: true,
        erl: true,
        erlang: true,
        f: true,
        "f#": true,
        f03: true,
        f08: true,
        f18: true,
        f77: true,
        f90: true,
        f95: true,
        fennel: true,
        fish: true,
        fluent: true,
        for: true,
        "fortran-fixed-form": true,
        "fortran-free-form": true,
        fs: true,
        fsharp: true,
        fsl: true,
        ftl: true,
        gdresource: true,
        gdscript: true,
        gdshader: true,
        genie: true,
        gherkin: true,
        "git-commit": true,
        "git-rebase": true,
        gjs: true,
        gleam: true,
        "glimmer-js": true,
        "glimmer-ts": true,
        glsl: true,
        gnuplot: true,
        go: true,
        gql: true,
        graphql: true,
        groovy: true,
        gts: true,
        hack: true,
        haml: true,
        handlebars: true,
        haskell: true,
        haxe: true,
        hbs: true,
        hcl: true,
        hjson: true,
        hlsl: true,
        hs: true,
        html: true,
        "html-derivative": true,
        http: true,
        hxml: true,
        hy: true,
        imba: true,
        ini: true,
        jade: true,
        java: true,
        javascript: true,
        jinja: true,
        jison: true,
        jl: true,
        js: true,
        json: true,
        json5: true,
        jsonc: true,
        jsonl: true,
        jsonnet: true,
        jssm: true,
        jsx: true,
        julia: true,
        kotlin: true,
        kql: true,
        kt: true,
        kts: true,
        kusto: true,
        latex: true,
        lean: true,
        lean4: true,
        less: true,
        liquid: true,
        lisp: true,
        lit: true,
        llvm: true,
        log: true,
        logo: true,
        lua: true,
        luau: true,
        make: true,
        makefile: true,
        markdown: true,
        marko: true,
        matlab: true,
        md: true,
        mdc: true,
        mdx: true,
        mediawiki: true,
        mermaid: true,
        mips: true,
        mipsasm: true,
        mmd: true,
        mojo: true,
        move: true,
        nar: true,
        narrat: true,
        nextflow: true,
        nf: true,
        nginx: true,
        nim: true,
        nix: true,
        nu: true,
        nushell: true,
        objc: true,
        "objective-c": true,
        "objective-cpp": true,
        ocaml: true,
        pascal: true,
        perl: true,
        perl6: true,
        php: true,
        plsql: true,
        po: true,
        polar: true,
        postcss: true,
        pot: true,
        potx: true,
        powerquery: true,
        powershell: true,
        prisma: true,
        prolog: true,
        properties: true,
        proto: true,
        protobuf: true,
        ps: true,
        ps1: true,
        pug: true,
        puppet: true,
        purescript: true,
        py: true,
        python: true,
        ql: true,
        qml: true,
        qmldir: true,
        qss: true,
        r: true,
        racket: true,
        raku: true,
        razor: true,
        rb: true,
        reg: true,
        regex: true,
        regexp: true,
        rel: true,
        riscv: true,
        rs: true,
        rst: true,
        ruby: true,
        rust: true,
        sas: true,
        sass: true,
        scala: true,
        scheme: true,
        scss: true,
        sdbl: true,
        sh: true,
        shader: true,
        shaderlab: true,
        shell: true,
        shellscript: true,
        shellsession: true,
        smalltalk: true,
        solidity: true,
        soy: true,
        sparql: true,
        spl: true,
        splunk: true,
        sql: true,
        "ssh-config": true,
        stata: true,
        styl: true,
        stylus: true,
        svelte: true,
        swift: true,
        "system-verilog": true,
        systemd: true,
        talon: true,
        talonscript: true,
        tasl: true,
        tcl: true,
        templ: true,
        terraform: true,
        tex: true,
        tf: true,
        tfvars: true,
        toml: true,
        ts: true,
        "ts-tags": true,
        tsp: true,
        tsv: true,
        tsx: true,
        turtle: true,
        twig: true,
        typ: true,
        typescript: true,
        typespec: true,
        typst: true,
        v: true,
        vala: true,
        vb: true,
        verilog: true,
        vhdl: true,
        vim: true,
        viml: true,
        vimscript: true,
        vue: true,
        "vue-html": true,
        vy: true,
        vyper: true,
        wasm: true,
        wenyan: true,
        wgsl: true,
        wiki: true,
        wikitext: true,
        wit: true,
        wl: true,
        wolfram: true,
        xml: true,
        xsl: true,
        yaml: true,
        yml: true,
        zenscript: true,
        zig: true,
        zsh: true,
        文言: true,
    },
};

export const SnippetContext = createContext<SnippetState>(
    defaultInitialSnippetState
);

type SnippetContextActions = {
    type: SnippetActions.setLanguageFilters;
    payload: SnippetState["languageFilter"];
};

export const SnippetDispatchContext = createContext<
    React.Dispatch<SnippetContextActions>
>(null!);

export const useSnippetContext = () => useContext(SnippetContext);
export const useSnippetDispatch = () => useContext(SnippetDispatchContext);

export const SnippetContextReducer = (
    state: SnippetState,
    action: SnippetContextActions
): SnippetState => {
    switch (action.type) {
        case SnippetActions.setLanguageFilters: {
            return {
                ...state,
                languageFilter: action.payload,
            };
        }
        default: {
            return state;
        }
    }
};

SnippetContextReducer.displayName = "SnippetContextReducer";
