// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TagEntity`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `get_mdx_note_join`, `new`, `new`, `to_front_matter_join`

class TagCreatable {
  final int? id;
  final String value;
  final String tagType;

  const TagCreatable({this.id, required this.value, required this.tagType});

  @override
  int get hashCode => id.hashCode ^ value.hashCode ^ tagType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagCreatable &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          value == other.value &&
          tagType == other.tagType;
}
