// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

class TaggableWithFrontMatterJoin {
  final int tagId;
  final int frontMatterId;

  const TaggableWithFrontMatterJoin({
    required this.tagId,
    required this.frontMatterId,
  });

  @override
  int get hashCode => tagId.hashCode ^ frontMatterId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaggableWithFrontMatterJoin &&
          runtimeType == other.runtimeType &&
          tagId == other.tagId &&
          frontMatterId == other.frontMatterId;
}
