[package]
name = "fluster_db"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
chrono = { workspace = true }
flutter_rust_bridge = { workspace = true }
gray_matter = { workspace = true }
serde = { workspace = true, features = ["derive"] }
surrealdb = { workspace = true, features = [
    "kv-surrealkv",
    "protocol-ws",
    "rustls",
] }
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
validator = "0.20.0"
fluster_types = { path = "../fluster_types/" }
dirs.workspace = true
log = "0.4.27"

[dev-dependencies]
fluster_test_utils = { path = "../fluster_test_utils" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
