// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/services/mdx_service/server.dart';
import 'api/services/mdx_service/server/mdx_proto.dart';
import 'api/services/settings_service/server.dart';
import 'api/services/settings_service/server/settings_proto.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SettingItemPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItemPtr;

  @protected
  SettingItem
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem(
    dynamic raw,
  );

  @protected
  SettingItem
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FrontMatter dco_decode_box_autoadd_front_matter(dynamic raw);

  @protected
  MdxNote dco_decode_box_autoadd_mdx_note(dynamic raw);

  @protected
  SettingItem dco_decode_box_autoadd_setting_item(dynamic raw);

  @protected
  SettingType dco_decode_box_autoadd_setting_type(dynamic raw);

  @protected
  File dco_decode_file(dynamic raw);

  @protected
  FrontMatter dco_decode_front_matter(dynamic raw);

  @protected
  GetUserSettingsResponse dco_decode_get_user_settings_response(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SettingField> dco_decode_list_setting_field(dynamic raw);

  @protected
  MdxNote dco_decode_mdx_note(dynamic raw);

  @protected
  MdxNoteResponse dco_decode_mdx_note_response(dynamic raw);

  @protected
  MdxServiceHandler dco_decode_mdx_service_handler(dynamic raw);

  @protected
  NoteSummary dco_decode_note_summary(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FrontMatter? dco_decode_opt_box_autoadd_front_matter(dynamic raw);

  @protected
  MdxNote? dco_decode_opt_box_autoadd_mdx_note(dynamic raw);

  @protected
  SettingType? dco_decode_opt_box_autoadd_setting_type(dynamic raw);

  @protected
  PathRequest dco_decode_path_request(dynamic raw);

  @protected
  SettingField dco_decode_setting_field(dynamic raw);

  @protected
  SettingItem dco_decode_setting_item(dynamic raw);

  @protected
  SettingServiceHandler dco_decode_setting_service_handler(dynamic raw);

  @protected
  SettingType dco_decode_setting_type(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  SettingItem
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem(
    SseDeserializer deserializer,
  );

  @protected
  SettingItem
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FrontMatter sse_decode_box_autoadd_front_matter(SseDeserializer deserializer);

  @protected
  MdxNote sse_decode_box_autoadd_mdx_note(SseDeserializer deserializer);

  @protected
  SettingItem sse_decode_box_autoadd_setting_item(SseDeserializer deserializer);

  @protected
  SettingType sse_decode_box_autoadd_setting_type(SseDeserializer deserializer);

  @protected
  File sse_decode_file(SseDeserializer deserializer);

  @protected
  FrontMatter sse_decode_front_matter(SseDeserializer deserializer);

  @protected
  GetUserSettingsResponse sse_decode_get_user_settings_response(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SettingField> sse_decode_list_setting_field(
    SseDeserializer deserializer,
  );

  @protected
  MdxNote sse_decode_mdx_note(SseDeserializer deserializer);

  @protected
  MdxNoteResponse sse_decode_mdx_note_response(SseDeserializer deserializer);

  @protected
  MdxServiceHandler sse_decode_mdx_service_handler(
    SseDeserializer deserializer,
  );

  @protected
  NoteSummary sse_decode_note_summary(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FrontMatter? sse_decode_opt_box_autoadd_front_matter(
    SseDeserializer deserializer,
  );

  @protected
  MdxNote? sse_decode_opt_box_autoadd_mdx_note(SseDeserializer deserializer);

  @protected
  SettingType? sse_decode_opt_box_autoadd_setting_type(
    SseDeserializer deserializer,
  );

  @protected
  PathRequest sse_decode_path_request(SseDeserializer deserializer);

  @protected
  SettingField sse_decode_setting_field(SseDeserializer deserializer);

  @protected
  SettingItem sse_decode_setting_item(SseDeserializer deserializer);

  @protected
  SettingServiceHandler sse_decode_setting_service_handler(
    SseDeserializer deserializer,
  );

  @protected
  SettingType sse_decode_setting_type(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem(
    SettingItem self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem(
    SettingItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_front_matter(
    FrontMatter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mdx_note(MdxNote self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_setting_item(
    SettingItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_setting_type(
    SettingType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file(File self, SseSerializer serializer);

  @protected
  void sse_encode_front_matter(FrontMatter self, SseSerializer serializer);

  @protected
  void sse_encode_get_user_settings_response(
    GetUserSettingsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_setting_field(
    List<SettingField> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mdx_note(MdxNote self, SseSerializer serializer);

  @protected
  void sse_encode_mdx_note_response(
    MdxNoteResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mdx_service_handler(
    MdxServiceHandler self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_summary(NoteSummary self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_front_matter(
    FrontMatter? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_mdx_note(
    MdxNote? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_setting_type(
    SettingType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_path_request(PathRequest self, SseSerializer serializer);

  @protected
  void sse_encode_setting_field(SettingField self, SseSerializer serializer);

  @protected
  void sse_encode_setting_item(SettingItem self, SseSerializer serializer);

  @protected
  void sse_encode_setting_service_handler(
    SettingServiceHandler self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_setting_type(SettingType self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItemPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_fluster_rpc_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItemPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItemPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_fluster_rpc_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItem =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSettingItemPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
