use chrono::Utc;

use super::equation_snippet_model::EquationSnippetModel;

pub struct EquationModel {
    /// This is the traditional id field, generated by uuid.
    pub id: Option<String>,
    /// The equation_id field is the 'id' field as provided from the user. This is used to
    /// reference equations throughout their notes in a way that makes sense to the user as
    /// opposed to an arbitrary string.
    pub equation_id: Option<String>,
    /// The title or label for the equation.
    pub label: String,
    /// The equation latex string.
    pub body: String,
    pub desc: String,
    pub snippets: Vec<EquationSnippetModel>,
    /// Time snippet is initially created.
    pub ctime: chrono::DateTime<Utc>,
    /// Time snippet is last updated.
    pub utime: chrono::DateTime<Utc>,
}
