[package]
name = "fluster"
version = "0.1.0"
description = "Free, open source academic note taking."
authors = ["Andrew Iglinski <fluster.eyeoh@gmail.com>"]
homepage = "https://fluster-one.vercel.app"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "fluster_lib"
crate-type = ["staticlib", "cdylib", "rlib"]


[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
plotly = { version = "0.12", features = [
    "kaleido",
    "kaleido_download",
    "plotly_ndarray",
] }
tauri = { version = "2", features = ["tray-icon", "specta", "test"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-deep-link = "2"
tauri-plugin-macos-permissions = "2.3.0"
tauri-plugin-dialog = "2"
tauri-plugin-devtools = "2.0.0"
typeshare = "1.0.4"
tauri-specta = { version = "=2.0.0-rc.21", features = ["derive", "typescript"] }
specta = { version = "=2.0.0-rc.22", features = ["chrono", "derive"] }
# fluster_test_utils = { path = "../../../packages/fluster_test_utils/" }
tauri-plugin-log = "2"
specta-typescript = "0.0.9"
log = "0.4.27"
crossbeam = { version = "0.8.4", features = [
    "alloc",
    "std",
    "crossbeam-channel",
] }
enum-iterator = "2.1.0"
regex = "1.11.1"
biblatex = { version = "0.10.0", features = ["serde"] }
dirs = "6.0.0"
tokio = { version = "1.45.0", features = ["fs", "full"] }
thiserror = "2.0.12"
gray_matter = "0.2.8"
ignore = "0.4.23"
filetime = "0.2.25"
strsim = "0.11.1"
crossbeam-channel = "0.5.15"
rayon = "1.10.0"
strum = "0.27.1"
strum_macros = "0.27.1"
sea-query = "0.32.5"
embed-file = "0.2.0"
include_dir = "0.7.4"
uuid = { version = "1.17.0", features = ["v4"] }
lancedb = { version = "0.19", features = ["polars"] }
chrono = { version = "0.4", features = ["now", "serde"] }
arrow-schema = "54.1"
arrow-array = "54.1"
ollama-rs = { version = "0.3.1", features = ["stream"] }
futures-util = "0.3.31"
futures = "0.3.31"
serde_arrow = { version = "0.13.3", features = ["arrow-54"] }
fast_qr = { version = "0.13.0", features = ["svg"] }
async-trait = "0.1.88"
tauri-plugin-network = "2.0.4"
schemars = { version = "0.9.0", features = ["chrono04", "preserve_order"] }
image = "0.25.6"
glob = "0.3.2"
sysinfo = { version = "0.35.2", features = [
    "apple-app-store",
    "multithread",
    "serde",
] }
langchain-rust = "4.6.0"
rig-lancedb = "0.2.11"
tantivy = "0.22.0"
rand = "0.9.1"
pyo3 = "0.25.1"
ndarray = { version = "0.16.1", features = ["rayon", "serde"] }
numpy = "0.25.0"
kalosm = { version = "0.4.0", features = ["full"] }

[target.'cfg(target_os = "macos")'.dependencies]
kalosm = { version = "0.4.0", features = ["full", "metal"] }


[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-window-state = "2"
