// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `handle_arr_data`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TagFromPodResult`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<Regex> getTagRegularExpression() => RustLib.instance.api
    .crateApiModelsTaggablesTaggableGetTagRegularExpression();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ParsedEntity>>
abstract class ParsedEntity implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Regex>>
abstract class Regex implements RustOpaqueInterface {}

class TagFromContentResult {
  final List<Taggable> tags;
  final String parsedContent;

  const TagFromContentResult({required this.tags, required this.parsedContent});

  @override
  int get hashCode => tags.hashCode ^ parsedContent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagFromContentResult &&
          runtimeType == other.runtimeType &&
          tags == other.tags &&
          parsedContent == other.parsedContent;
}

class Taggable {
  final String value;
  final TaggableType tagType;

  const Taggable({required this.value, required this.tagType});

  static Future<TagFromContentResult> fromMdxContent({
    required ParsedEntity data,
  }) => RustLib.instance.api
      .crateApiModelsTaggablesTaggableTaggableFromMdxContent(data: data);

  static Future<List<Taggable>> fromPodData({required ParsedEntity data}) =>
      RustLib.instance.api.crateApiModelsTaggablesTaggableTaggableFromPodData(
        data: data,
      );

  @override
  int get hashCode => value.hashCode ^ tagType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Taggable &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          tagType == other.tagType;
}

enum TaggableType { tag, subject, topic }
