#!/bin/bash

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
    echo "You can't commit directly to $branch branch Einstein..."
    exit 1
fi

dotenvx ext precommit

pnpm syncpack format

git add "$FLUSTER_NATIVE_ROOT/packages/*/package.json"

cargo doc --workspace

cargo fmt --manifest-path "$FLUSTER_NATIVE_ROOT/packages/fluster_db/Cargo.toml"
cargo fmt --manifest-path "$FLUSTER_NATIVE_ROOT/packages/fluster_rust_types/Cargo.toml"
cargo fmt --manifest-path "$FLUSTER_NATIVE_ROOT/packages/fluster_grpc/Cargo.toml"
cargo fmt --manifest-path "$FLUSTER_NATIVE_ROOT/packages/fluster_native_interface/rust/Cargo.toml"

gt add "$FLUSTER_NATIVE_ROOT/packages/fluster_db/Cargo.toml"
gt add "$FLUSTER_NATIVE_ROOT/packages/fluster_rust_types/Cargo.toml"
gt add "$FLUSTER_NATIVE_ROOT/packages/fluster_grpc/Cargo.toml"
gt add "$FLUSTER_NATIVE_ROOT/packages/fluster_native_interface/rust/Cargo.toml"
