name: fluster_ui
description: Fluster UI widgets
version: 0.0.1
homepage: ulld.vercel.app
environment:
  sdk: ^3.7.2
  
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
