// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../nested_models/code/supported_syntax_language.dart';
import '../snippet/snippet_model.dart';
import '../taggable/tag_model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class EquationEntity {
  final String? id;
  final String label;
  final String body;
  final List<Snippet> code;

  const EquationEntity({
    this.id,
    required this.label,
    required this.body,
    required this.code,
  });

  static Future<EquationEntity> default_() => RustLib.instance.api
      .crateApiModelsEquationEquationModelEquationEntityDefault();

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ body.hashCode ^ code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EquationEntity &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          body == other.body &&
          code == other.code;
}
