import "@fluster.io/dev/themes.css";
import "./globals.scss";
import localFont from "next/font/local";
import FumaDocsProvider from "#/features/docs/fuma_docs_provider";

const appFont = localFont({
    variable: "--ulld-app-font",
    src: [
        {
            path: "../../assets/appFont/DM_Sans/static/DMSans-Thin.ttf",
            weight: "100",
            style: "normal",
        },
        {
            path: "../../assets/appFont/DM_Sans/static/DMSans-Bold.ttf",
            weight: "700",
            style: "normal",
        },
        {
            path: "../../assets/appFont/DM_Sans/static/DMSans-Light.ttf",
            weight: "300",
            style: "normal",
        },
        {
            path: "../../assets/appFont/DM_Sans/static/DMSans-Regular.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../assets/appFont/DM_Sans/static/DMSans-Italic.ttf",
            weight: "400",
            style: "italic",
        },
        {
            path: "../../assets/appFont/DM_Sans/static/DMSans-SemiBold.ttf",
            weight: "600",
            style: "normal",
        },
        {
            path: "../../assets/appFont/DM_Sans/static/DMSans-ExtraBold.ttf",
            weight: "800",
            style: "normal",
        },
    ],
    display: "swap",
});

/* export const metadata: Metadata = { */
/*     title: "Create Next App", */
/*     description: "Generated by create next app", */
/* }; */

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={appFont.variable}>
            <body className={`antialiased background`}>
                <FumaDocsProvider>
                    <div>{children}</div>
                </FumaDocsProvider>
            </body>
        </html>
    );
}
