// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

enum DbTokenizerLanguage {
  arabic,
  danish,
  dutch,
  english,
  french,
  german,
  greek,
  hungarian,
  italian,
  norwegian,
  portuguese,
  romanian,
  russian,
  spanish,
  swedish,
  tamil,
  turkish;

  static Future<DbTokenizerLanguage> default_() => RustLib.instance.api
      .crateApiRepositoriesNotesMdxQueryParamsDbTokenizerLanguageDefault();
}

class MdxNoteQueryParams {
  final String query;
  final DbTokenizerLanguage language;

  const MdxNoteQueryParams({required this.query, required this.language});

  @override
  int get hashCode => query.hashCode ^ language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MdxNoteQueryParams &&
          runtimeType == other.runtimeType &&
          query == other.query &&
          language == other.language;
}
